/**
 * YAML and eval-pack templates shared by `verdict init` and `verdict
 * onboarding`. Rendered via string templating, NOT `js-yaml` — the latter
 * strips comments, which matter here for user-facing docs in the file.
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { Plan } from './events.js'

// ─── verdict.yaml ───────────────────────────────────────────────────────────

export interface VerdictYamlOptions {
  name?: string
  /** Local Ollama models to add. */
  ollamaModels: Array<{ id: string; model: string; tags?: string[]; moe?: boolean }>
  /** MLX models to add. */
  mlxModels?: Array<{ id: string; model: string; tags?: string[] }>
  /** Cloud models (api_key resolves to ${ENV_VAR}). */
  cloudModels: Array<{
    id: string
    base_url: string
    apiKeyEnv: string
    model: string
    costPer1mInput?: number
    costPer1mOutput?: number
    tags?: string[]
  }>
  /** The model id (one of the ids above) to use as judge. */
  judgeModelId: string
  /** Concurrency for `run:`. Default 3. */
  concurrency?: number
}

export function renderVerdictYaml(opts: VerdictYamlOptions): string {
  const concurrency = opts.concurrency ?? 3
  const ollamaBlock = opts.ollamaModels
    .map(m => {
      const tags = m.tags?.length ? `\n    tags: [${m.tags.join(', ')}]` : ''
      const note = m.moe ? '\n    timeout_ms: 180000  # MoE: long timeout' : ''
      return [
        `  - id: ${m.id}`,
        `    provider: ollama`,
        `    model: ${m.model}`,
        `    host: "\${OLLAMA_HOST:-localhost:11434}"${tags}${note}`,
      ].join('\n')
    })
    .join('\n')

  const mlxBlock = (opts.mlxModels ?? [])
    .map(m => {
      const tags = m.tags?.length ? `\n    tags: [${m.tags.join(', ')}]` : ''
      return [
        `  - id: ${m.id}`,
        `    provider: mlx`,
        `    model: ${m.model}`,
        `    port: "\${MLX_PORT:-8080}"${tags}`,
      ].join('\n')
    })
    .join('\n')

  const cloudBlock = opts.cloudModels
    .map(m => {
      const tags = m.tags?.length ? `\n    tags: [${m.tags.join(', ')}]` : ''
      const cost = m.costPer1mInput !== undefined && m.costPer1mOutput !== undefined
        ? `\n    cost_per_1m_input: ${m.costPer1mInput}\n    cost_per_1m_output: ${m.costPer1mOutput}`
        : ''
      return [
        `  - id: ${m.id}`,
        `    base_url: "${m.base_url}"`,
        `    api_key: "\${${m.apiKeyEnv}}"`,
        `    model: "${m.model}"${cost}${tags}`,
      ].join('\n')
    })
    .join('\n')

  const modelsSection = [ollamaBlock, mlxBlock, cloudBlock].filter(Boolean).join('\n\n')

  return `# verdict.yaml
# All values support \${ENV_VAR} and \${ENV_VAR:-default} substitution.
# Generated by verdict — edit freely.
version: "1.0"
name: "${opts.name ?? 'My Evals'}"

models:
${modelsSection}

judge:
  model: ${opts.judgeModelId}
  blind: true
  rubric:
    accuracy: 0.4
    completeness: 0.4
    conciseness: 0.2

packs:
  - ./eval-packs/general.yaml

run:
  concurrency: ${concurrency}
  retries: 2
  cache: true

output:
  dir: ./results
  formats: [json, markdown]
`
}

/**
 * Render verdict.yaml directly from a Plan. Convenience over `renderVerdictYaml`
 * — the planner already chose the models and judge, so we just need to map the
 * structures.
 */
export function renderVerdictYamlFromPlan(plan: Plan, name = 'My Evals'): string {
  const ollamaModels = [
    ...plan.modelsToPull.map(m => ({
      id: idFromModelName(m.name),
      model: m.name,
      tags: rolesToTags(m.role),
    })),
    ...plan.reuseModels.map(m => ({
      id: idFromModelName(m),
      model: m,
      tags: ['local', 'free'],
    })),
  ]
  const cloudModels = plan.cloudModels.map(m => ({
    id: m.id,
    base_url: m.base_url,
    apiKeyEnv: m.apiKeyEnv,
    model: m.model,
    costPer1mInput: m.costPer1mInput,
    costPer1mOutput: m.costPer1mOutput,
    tags: ['cloud'],
  }))
  return renderVerdictYaml({
    name,
    ollamaModels,
    cloudModels,
    judgeModelId: plan.judge.modelId,
  })
}

function rolesToTags(role: string): string[] {
  switch (role) {
    case 'general-small': return ['local', 'free', 'fast', 'general']
    case 'general-mid':   return ['local', 'free', 'general']
    case 'coder':         return ['local', 'free', 'coding']
    case 'judge':         return ['local', 'free', 'judge']
    default:              return ['local', 'free']
  }
}

export function idFromModelName(name: string): string {
  // Keep family + variant + size tag (qwen2.5-coder:7b → qwen2-5-coder-7b).
  // Strip path prefix on MLX models (mlx-community/Foo-4bit → foo-4bit).
  const stripped = name.includes('/') ? name.split('/').pop()! : name
  return stripped.replace(/[^a-z0-9]/gi, '-').replace(/^-+|-+$/g, '').toLowerCase()
}

// ─── eval-packs/general.yaml ────────────────────────────────────────────────

export const GENERAL_PACK = `# eval-packs/general.yaml
name: General
version: 1.0.0
description: 10 general-purpose cases covering factual recall, reasoning, coding, and instruction following

cases:
  - id: gen-001
    prompt: "What is the capital of France?"
    criteria: "Single correct answer: Paris"
    tags: [factual, easy]

  - id: gen-002
    prompt: "What does RAM stand for and what does it do?"
    criteria: "Random Access Memory, volatile storage that holds running programs and data"
    tags: [factual, cs]

  - id: gen-003
    prompt: "Explain the difference between a process and a thread in one paragraph."
    criteria: "Covers: separate memory space vs shared, overhead difference, use cases for each"
    tags: [technical, cs]

  - id: gen-004
    prompt: "If all mammals are warm-blooded, and dolphins are mammals, what can we conclude about dolphins?"
    criteria: "Correct deductive conclusion: dolphins are warm-blooded. Clear reasoning shown."
    tags: [reasoning, logic]

  - id: gen-005
    prompt: "List exactly 3 benefits of regular exercise. Numbered list. Max 12 words per item."
    criteria: "Exactly 3 items, numbered list format, each under 12 words"
    tags: [instruction-following]

  - id: gen-006
    prompt: "Write a JavaScript function that returns the sum of all even numbers in an array."
    criteria: "Working JS function, handles empty array, filters even numbers with % 2 === 0, returns sum"
    tags: [coding, javascript]

  - id: gen-007
    prompt: "What is the time complexity of binary search and why?"
    criteria: "O(log n), correct explanation of halving the search space each iteration"
    tags: [cs, algorithms]

  - id: gen-008
    prompt: "Explain what a transformer model is in 2-3 sentences for a software engineer who knows ML basics."
    criteria: "Covers attention mechanism, parallel processing (vs RNN), why it improved NLP. Appropriate depth."
    tags: [ml, explanation]

  - id: gen-009
    prompt: "Write a haiku about debugging code."
    criteria: "5-7-5 syllable structure, references debugging or code, coherent meaning"
    tags: [creative, instruction-following]

  - id: gen-010
    prompt: "What is the CAP theorem and what does it mean for distributed systems design?"
    criteria: "Consistency, Availability, Partition tolerance, can only guarantee 2 of 3, tradeoffs for system design"
    tags: [cs, distributed-systems]
`

// ─── eval-packs/moe.yaml ────────────────────────────────────────────────────

export const MOE_PACK = `# eval-packs/moe.yaml
name: MoE Benchmark
version: 1.0.0
description: Tasks that highlight Mixture-of-Experts model strengths. MoE models activate different experts per token, excelling at tasks that require switching between domains.

cases:
  - id: moe-001
    prompt: "Explain how mRNA vaccines work, then write a Python function that simulates a simple S-curve adoption model."
    criteria: "Correct mRNA mechanism (spike protein, immune training). Working Python S-curve function (sigmoid or logistic), accepts time parameter."
    tags: [multi-domain, biology, coding]

  - id: moe-002
    prompt: "Solve: if x^2 - 5x + 6 = 0, find x. Then describe one real-world system this equation could model."
    criteria: "Correct roots: x=2, x=3. Reasonable real-world application (spring, projectile, population model, etc.)"
    tags: [math, reasoning, applied]

  - id: moe-003
    prompt: "Translate this Python code to TypeScript, then explain the main type safety difference: def add(a, b): return a + b"
    criteria: "Correct TypeScript with type annotations (number params + return type). Explanation mentions static typing."
    tags: [coding, multi-language]

  - id: moe-004
    prompt: "Describe the French Revolution in 3 sentences, then identify 2 parallels to a modern political movement."
    criteria: "Historically accurate summary. Two specific, defensible modern parallels named."
    tags: [history, analysis, reasoning]

  - id: moe-005
    prompt: "Write a SQL query to find the top 3 customers by revenue from an orders table (customer_id, amount, date). Then explain what index would speed it up."
    criteria: "Correct SQL with GROUP BY, SUM, ORDER BY DESC, LIMIT 3. Reasonable index suggestion (customer_id or composite)."
    tags: [coding, sql, performance]
`

// ─── eval-packs/quantization.yaml ──────────────────────────────────────────

export const QUANTIZATION_PACK_STUB = `# eval-packs/quantization.yaml
name: Quantization
version: 1.0.0
description: Minimal fallback pack for checking structured output degradation.

cases:
  - id: quant-001
    prompt: "Return only this JSON object: {\"status\":\"ok\",\"count\":3}"
    criteria: "Valid JSON only, exact status and count fields"
    scorer: json
    expected: "{\"status\":\"ok\",\"count\":3}"
    tags: [json, structured-output, quantization-sensitive]
`

export function loadQuantizationPack(): string | null {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const candidates = [
    path.resolve(here, '..', '..', 'eval-packs', 'quantization.yaml'),
    path.resolve(process.cwd(), 'eval-packs', 'quantization.yaml'),
  ]

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return fs.readFileSync(candidate, 'utf8')
  }

  return null
}

// ─── .env.example ───────────────────────────────────────────────────────────

export const ENV_EXAMPLE = `# verdict environment variables
OPENROUTER_API_KEY=your_key_here
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GROQ_API_KEY=gsk_...
# OLLAMA_HOST=localhost:11434
# MLX_PORT=8080
`
