/**
 * verdictScore — zero-config inline eval for single responses
 *
 * Score a single model response without needing a config file or eval pack.
 * Perfect for inline assertions in existing tests or scripts.
 *
 * @example
 * ```ts
 * import { verdictScore } from 'verdict'
 *
 * const score = await verdictScore({
 *   model: {
 *     base_url: 'http://localhost:11434/v1',
 *     api_key: 'none',
 *     model: 'llama3.1:8b',
 *   },
 *   judge: {
 *     base_url: 'https://api.openai.com/v1',
 *     api_key: process.env.OPENAI_API_KEY,
 *     model: 'gpt-4o-mini',
 *   },
 *   prompt: 'Summarize this document...',
 *   response: actualOutput,
 *   criteria: 'Accurate, concise summary covering the main points',
 * })
 *
 * console.log(score.total)      // e.g. 8.2
 * expect(score.total).toBeGreaterThan(7)
 * ```
 */

import OpenAI from 'openai'
import { judgeResponse } from './judge/llm.js'
import type { JudgeScore, ModelConfig, JudgeConfig } from './types/index.js'

export interface VerdictScoreModelOptions {
  /** OpenAI-compat base URL, e.g. 'http://localhost:11434/v1' */
  base_url: string
  /** API key. Use 'none' or omit for local models */
  api_key?: string
  /** Model name, e.g. 'llama3.1:8b' */
  model: string
  /** Optional max tokens for the model call */
  max_tokens?: number
}

export interface VerdictScoreJudgeOptions {
  /** OpenAI-compat base URL for the judge */
  base_url?: string
  /** API key for the judge. Defaults to OPENAI_API_KEY env var */
  api_key?: string
  /** Judge model name. Defaults to 'gpt-4o-mini' */
  model?: string
  /** Scoring rubric weights (must sum to 1.0). Defaults to 0.4/0.4/0.2 */
  rubric?: {
    accuracy?: number
    completeness?: number
    conciseness?: number
  }
}

export interface VerdictScoreOptions {
  /** Model to score (call + judge) */
  model: VerdictScoreModelOptions
  /** Judge model config. Defaults to OpenAI gpt-4o-mini via OPENAI_API_KEY */
  judge?: VerdictScoreJudgeOptions
  /** The prompt/question sent to the model */
  prompt: string
  /** The response to evaluate. If omitted, verdict will call the model to get a response */
  response?: string
  /** Criteria for evaluation */
  criteria: string
}

export interface VerdictScoreResult extends JudgeScore {
  /** The response that was scored */
  response: string
  /** Whether the response was generated by verdict (true) or provided by caller (false) */
  generated: boolean
}

/**
 * Score a single model response using the verdict judge.
 * Zero configuration required — no config file, no eval pack.
 */
export async function verdictScore(options: VerdictScoreOptions): Promise<VerdictScoreResult> {
  const { model, judge = {}, prompt, criteria } = options
  let response = options.response
  let generated = false

  // If no response provided, call the model to get one
  if (!response) {
    const client = new OpenAI({
      baseURL: model.base_url,
      apiKey: model.api_key === 'none' || !model.api_key ? 'no-key-required' : model.api_key,
      timeout: 60_000,
    })

    const result = await client.chat.completions.create({
      model: model.model,
      messages: [{ role: 'user', content: prompt }],
      max_tokens: model.max_tokens ?? 1024,
    })

    response = result.choices[0]?.message?.content ?? ''
    generated = true
  }

  // Build judge config
  const judgeBaseUrl = judge.base_url ?? 'https://api.openai.com/v1'
  const judgeApiKey = judge.api_key ?? process.env.OPENAI_API_KEY ?? 'no-key-required'
  const judgeModel = judge.model ?? 'gpt-4o-mini'

  const judgeModelConfig: ModelConfig = {
    id: 'inline-judge',
    base_url: judgeBaseUrl,
    api_key: judgeApiKey,
    model: judgeModel,
    tags: [],
    timeout_ms: 30_000,
    max_tokens: 256,
    port: 8080,
  }

  const judgeConfig: JudgeConfig = {
    model: judgeModel,
    blind: true,
    strategy: 'single',
    rubric: {
      accuracy: judge.rubric?.accuracy ?? 0.4,
      completeness: judge.rubric?.completeness ?? 0.4,
      conciseness: judge.rubric?.conciseness ?? 0.2,
    },
  }

  const score = await judgeResponse(judgeModelConfig, judgeConfig, prompt, criteria, response)

  return {
    ...score,
    response,
    generated,
  }
}
